Homework 2
thebluecat5445/nha-oop-assignments pull request #3
Opened 2016-09-23 23:27 UTC by thebluecat5445

2016-09-23 23:27 UTC, thebluecat5445 commented
@rickyc I did it

2016-09-25 00:39 UTC, rickyc commented on Homework2.html
> +        return "<li>" + this.name + ": $" + this.price + "</li>"
ES6 string interpolation.

2016-09-25 00:40 UTC, rickyc commented on Homework2.html
> +        $("#" + this.name + "List").empty();
ES6 Strings

2016-09-25 00:44 UTC, rickyc requested changes
Close a few more things to solve.

2016-09-25 00:44 UTC, rickyc commented
## Homework 2
* [X] Does the application work?
* [X] Is there a HTML / CSS form to create Products?
* [X] Are the Product data saved on the server side (CloudBoost)?
* [X] When I refresh the page, do I see all the products displayed?
* [ ] Can I delete a specific product?
* [X] Is the code written using classes?
* [ ] Does the code make use of conditional selectors?
* [ ] Is there a map that displays all the stores location?
* [X] ~~Does the application make use of getters / setters?~~
* [X] Does the application make use of constructors?
* [X] Does the application properly use const, let and vars?
* [ ] Does the application use proper ES6 syntax? String interpolation, functions.
* [ ] Does it follow the JavaScript code guide conventions?

_Advanced Challenges (Optional)_
* [ ] Are the classes separated into individual files?
* [ ] Is there a Store object on CloudBoost.io?
* [ ] Does the Product / Store object have nested associations?
* [ ] Can the user edit products in the store?
* [ ] Does the code use bootstrap CSS / conventions?

2016-10-23 18:55 UTC, rickyc commented
@thebluecat5445 You can merge this one. Make sure you know how to delete products and use conditional selectors. You never addressed those two. 😠

2016-10-23 19:42 UTC, thebluecat5445 commented
@rickyc I think I got everything

2016-10-23 19:43 UTC, merged

2016-10-23 20:07 UTC, rickyc commented on Homework2.html
> +    function createNewProduct() {
You don't have to do it for this one, but something to note for the future. You know how there's the `Appdelegate` / `RootViewController` in iOS? You should create a class similar to that to hold all this logic.

2016-10-23 20:13 UTC, thebluecat5445 commented on Homework2.html
> +    function createNewProduct() {
Ok, thanks for the feedback :)